# Workflow for basic library builds.
name: Snapshot
on:
    push:
        branches:
            - main
jobs:
    # Build workflow.
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out sources
              uses: actions/checkout@v6
            - name: Setup Java JDK
              uses: actions/setup-java@v5.0.0
              with:
                  java-version: 25
                  distribution: temurin
            - name: Build and publish to GitHub Packages
              run: mvn deploy --settings .github/settings.xml -B --file pom.xml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ACTOR: ${{ github.actor }}
    # Documentation workflow.
    doc:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out sources
              uses: actions/checkout@v6
            - name: Setup Java JDK
              uses: actions/setup-java@v5.0.0
              with:
                  java-version: 25
                  distribution: temurin
            - name: Update the website
              run: mvn clean site site:stage -B
            - name: GitHub Pages action
              uses: peaceiris/actions-gh-pages@v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./target/staging
